basePath: /v1/api
host: localhost:9999
info:
  contact: {}
  description: '这是一个RBAC权限管理系统接口文档，访问地址是: localhost:9999/docs/swagger/index.html'
  termsOfService: https://github.com/lightsaid/grbac-vue
  title: 权限管理系统接口文档
  version: "1.0"
paths: {}
swagger: "2.0"
