## up: 在后台启动 docker compose 构建基础环境
up:
	docker-compose up -d

## down: 停止 docker compose
down:
	docker-compose down

## serve: 启动服务
serve:
	go run ./cmd/server/*.go

## doc: swag init
doc:
	swag init

.PHONY: up down run doc